{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: travelo-mysql-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "travelo.mysql.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
{{- end }}
